### ISSUE TITLE
Investigate the use of Red Panda as a Kakfa replacement

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#690]

**Comment by agaldemas** [comment]
çà a l'air d'avoir la patate Redpanda !
if you want we can try to include it, as it's Kafka compatible, an helm chart is provided, and it seems well documented !

**Comment by bobeal** [comment]
> if you want we can try to include it, as it's Kafka compatible, an helm chart is provided, and it seems well documented !

It would be very nice :) 

I've just played with it locally and it worked out of the box with Stellio (but I've not done extensive testing). It also has advantage to distribute ARM64 compatible Docker images, which is nice for people developing on a M1 MacBook...

**Comment by bobeal** [comment]
Basic configuration that is working with Stellio in docker-compose configuration:

```
  redpanda:
    image: vectorized/redpanda:v22.1.4
    container_name: stellio-redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:29092
    ports:
      - "9092:9092"
      - "29092:29092"
```

However, I encountered this issue: https://github.com/redpanda-data/redpanda/issues/5183

As a temporary workaround, I set manually the correct configuration in the container:

```
docker exec -it stellio-redpanda bash
redpanda@94b720440b68:/$ rpk cluster config set auto_create_topics_enabled true
```

Tried adding the property (https://docs.redpanda.com/docs/reference/cluster-properties/#topics-and-partitions) in docker-compose config but that did not work (RedPanda refused to start because it did not recognize the property name).
