### ISSUE TITLE
DataBufferLimitException in api gateway when uploading large content : envisage to have a variable to set "spring.codec.max-in-memory-size"

### ISSUE THREAD

**Issue by agaldemas** [stellio-hub/stellio-context-broker#701]
Hi we faced the following issues, with the API gateway, when posting a large content :
Caused by: org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144

I tried to add a variable` SPRING_CODEC_MAX-IN-MEMORY-SIZE: 10MB` in stellio-configmap.yaml, to get `spring.codecs.max-in-memory-size` configured but it's not taken in count through deployment with kubernetes...
in stellio/api-gateway-deployment.yaml, I added : 
```
   env:
        - name: SPRING_CODEC_MAX-IN-MEMORY-SIZE
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: SPRING_CODEC_MAX-IN-MEMORY-SIZE

```

but don't see the variable with env in the pod ?... and I don't think it translate the environment variable...

it is written in a post about spring configuration that it can be configured in application.yaml : with 
```
spring:
  codec:
      max-in-memory-size: 10MB
```
or by giving the variable in start command line something like :

 `java -Dspring.application.json='{"codec":{"max-in-memory-size":"10MB"}}' -jar myapp.jar`
